### ISSUE TITLE
`Wrong type argument: user-ptrp, nil`

### ISSUE THREAD

**Issue by alhassy** [isamert/jsdoc.el#1]
It looks like a neato package and I'd love to try it out.

When I try to use the package, as shown in the README, I get a `Wrong type argument: user-ptrp, nil` error.

Any assistance would be appreciated.

**Comment by isamert** [comment]
Hi @alhassy, thanks for trying out the package! 

Are you trying the exact same snippet from the README or can you post the one that you are using? And where do you put the cursor before calling `jsdoc` command? Also can you run `toggle-debug-on-error` and post the error output after calling `jsdoc`?

**Comment by Aankhen** [comment]
Same issue here. I installed the library with straight.el instead of with quelpa:
```emacs-lisp
(use-package jsdoc
  :straight (jsdoc :host github :repo "isamert/jsdoc.el"))
```
I also:
1. Installed tree-sitter.
2. Installed tree-sitter-langs and the grammars.
3. Enabled tree-sitter-mode.
4. Enabled tree-sitter-hl-mode.

I can see tree-sitter doing its thing, and run queries like in its documentation, so that seems fine. But even after all this, I get the `user-ptrp` error when placing my cursor on any of the first three words in this snippet and running <kbd>M-x jsdoc</kbd>:
```javascript
export function dynamic(coll, pre, logic) {
}
```
If I try with a `const`:
```javascript
const dynamic = function(foo) {
};
```
Running jsdoc with my cursor on the `const` raises an `Invalid function: 'identifier` error, while running it with my cursor on `dynamic` returns the same `user-ptrp` error.

This is the stack when I turn on `debug-on-error`:
```
Debugger entered--Lisp error: (wrong-type-argument user-ptrp nil)
  tsc-node-type(nil)
  jsdoc--infer-type(nil)
  jsdoc--get-return-type(#<user-ptr ptr=0000000007cf7150 finalizer=00007ffe42d49c50>)
  jsdoc--parse-arrow-function(#<user-ptr ptr=0000000007cf7150 finalizer=00007ffe42d49c50> "dynamic")
  jsdoc--parse-lexical-declaration(#<user-ptr ptr=0000000007cf6b90 finalizer=00007ffe42d49c50>)
  jsdoc--generate()
  jsdoc()
  funcall-interactively(jsdoc)
  call-interactively(jsdoc record nil)
  command-execute(jsdoc record)
  execute-extended-command(nil "jsdoc" #("jsdoc" 0 5 (face nil)))
  funcall-interactively(execute-extended-command nil "jsdoc" #("jsdoc" 0 5 (face nil)))
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```
I’m using the latest Git versions of all the aforementioned packages. Emacs 27.2, Windows 10 x64 (official build).

**Comment by isamert** [comment]
Thanks for the detailed information @Aankhen, I will try to reproduce it as soon as possible.

**Comment by isamert** [comment]
@Aankhen, @alhassy Can you try again with the latest changes, it should fix the issue.

**Comment by Aankhen** [comment]
Sorry to say there doesn’t seem to be any change. 😟 I updated the library, restarted Emacs, and tried [the same examples as before](https://github.com/isamert/jsdoc.el/issues/1#issuecomment-967037560) after verifying that I was running the new code, but I saw exactly the same errors.

**Comment by isamert** [comment]
@Aankhen Are you sure that `tree-sitter-mode` is enabled on the buffer? I get the exact same error if it's not enabled on the buffer but when it's enabled it works as expected.

**Comment by Aankhen** [comment]
Yup, it’s enabled. Could we be using different versions? I’m on v0.15.2, apparently.

**Comment by isamert** [comment]
I'm also on that version. I also made a few more changes regarding the `'identifier` error you are getting, I missed that on first fix. Can you try it again?

I also made sure that it works with vanilla Emacs this time, with the following configuration. You can confirm if it works for you this way, if my latest fix does not work for you:

- Start emacs with `emacs -Q`
- Eval the following (I'm not really familiar with straight, so I might be missing something or doing some unnecessary work. You may also need to clear your straight cache before I believe):
```elisp
(require 'package)

(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))

(package-initialize)
(package-refresh-contents)

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(package-install 'use-package)
(require 'use-package)

(use-package jsdoc :straight (jsdoc :host github :repo "isamert/jsdoc.el"))
(require 'jsdoc)
(require 'tree-sitter)
(require 'tree-sitter-langs)
```
- Open a js file and enable `tree-sitter-mode`.
- Paste your example from above.
- Run `jsdoc` on one of the js functions.

It runs successfully at this point.

**Comment by Aankhen** [comment]
Thank you for the detailed instructions. I noticed you seem to have `tree-sitter-langs` installed already, whereas I had to install it before the `require` would work. If I add the installation step and then proceed as outlined, I get the same error as before. Could it be a difference in the version of `tree-sitter-langs`’s grammar itself, if you’re using one that’s bundled with Emacs or something? The one I’ve been installing is [v0.10.7](https://github.com/emacs-tree-sitter/tree-sitter-langs/releases/tag/0.10.7).

**Comment by isamert** [comment]
I also have the same version, probably it just fetched it from my cache and I don't believe that's the reason why jsdoc is failing. How do you update jsdoc using straight? I just bumped the package version to `0.2`, can you upgrade to it and make sure that it's running the `0.2` version (version is defined on the line 6 of the package).

I'll try to reproduce everything by clearing my cache sometime today but for now I can't really reproduce the error.

**Comment by Aankhen** [comment]
`straight-pull-package` will update the package to the latest version. FWIW, I always check the Git log for jsdoc.el to make sure it was at the latest version before trying anything. (I can see that it’s now pulled in one new commit to bump the version.)

This really is quite a strange error. Thank for the time you’ve already spent trying to get to the bottom of it. I’ll try diving into the tree-sitter side of things to see if I can figure anything out.

**Comment by Aankhen** [comment]
It works! I have no idea what changed, but it works! I was restarting Emacs to figure out an unrelated annoyance, and when I returned to this issue, I saw that evaluating the `use-package` form to load jsdoc.el spent more than a second on the ‘Building’ stage before returning `nil`, instead of immediately returning `nil`. After that, the `jsdoc` command began working perfectly, as far as I can tell.

If I were to hazard a guess, I’d say the source files were updated to the newest versions as I said but the old .elc files were still being loaded, so the most recent problem was on my end. I apologize if that was the case. Thank you for the actual fix (probably 8e8d826e3d1fb58abb4766b9c218c3a4aeef10d0), and for your patience. I’m glad I can finally take advantage of this very useful library.

**Comment by isamert** [comment]
Great! No problem at all, I fixed another issue while trying to figure out the problem on `emacs -q`, so it's worth it. I need to warn you that the package is kinda half-baked, so I'm open to other feedbacks/bug reports that you may have in the future while using it.

> ...I was restarting Emacs to figure out an unrelated annoyance

Very relatable btw :)

**Comment by Aankhen** [comment]
Noted. It seems perfectly fine so far, but I’ll be sure to open issues if and when I run into any. Thanks again.
