### ISSUE TITLE
M-x jsdoc fails with "No available parser for this buffer"

### ISSUE THREAD

**Issue by jgonggrijp** [isamert/jsdoc.el#8]
I tried using `jsdoc` but could not get it to work. I'm still a relative beginner with emacs so I might very well be doing something wrong. I hope you can help me get it to work.

*emacs version:* 29.4

*init.el (relevant excerpts)*

(Listing all my packages in case it helps. All packages updated today.)

```lisp
(custom-set-variables
 '(package-selected-packages
   '(jsdoc company-quickhelp auctex company-web mocha-snippets yasnippet-snippets yasnippet smartparens treemacs-magit lua-mode mustache-mode multiple-cursors which-key company moonscript handlebars-mode sass-mode pyvenv ini-mode yarn-mode dockerfile-mode docker-compose-mode docker typescript-mode editorconfig vterm magit-gitflow magit ttl-mode projectile treemacs treemacs-projectile coffee-mode markdown-mode auto-dark))
 '(use-package-always-defer t))

(use-package jsdoc
  :commands jsdoc)
```

All packages updated today.

*code (point is at the `c` of `const`)*

```js
const columnProperties = {
    type: {},
    /* more stuff */
};
```

*command*

`M-x jsdoc`

*output in echo area*

`treesit-node-at: No available parser for this buffer: #<buffer tabulator-utils.js>`

**Comment by isamert** [comment]
Hmm, that sounds like mode issue. You need to be in `js-ts-mode` (instead of `javascript-mode`) to use jsdoc command. This is required because jsdoc utilizes treesitter to parse the code. Another benefit is that treesitter modes are _generally_ better at highlighting and they are a bit faster too.

The following link might help about the treesit and how it's used in Emacs (it shows how to make treesit mode variations to be the default and how you can install grammers etc.): https://www.masteringemacs.org/article/how-to-get-started-tree-sitter
